### ISSUE TITLE
Subset of pairwise interactions?

### ISSUE THREAD

**Issue by lang-benjamin** [mayer79/hstats#115]
Suppose X contains X_1, ..., X_p. I am interested in pairwise interaction strengths, but only the interaction between X_1 and X_j, for j=2, ..., p (i.e. all interactions compared to some reference variable). Is there a way to calculate only those interactions and omit all others?

**Comment by mayer79** [comment]
Currently not, I am afraid. If running pairwise stats is too costly, this solution should work:

```r
library(ranger)
library(hstats)

fit <- ranger(Sepal.Width ~ ., data = iris)
v1 <- "Sepal.Length"
v <- c("Species", "Petal.Length", "Petal.Width")

one_pairwise <- function(v2, fit, data, v1, ...) {
  h2_pairwise(hstats(fit, X = data, v = c(v1, v2), ...))$M
}

sapply(v, one_pairwise, fit = fit, data = iris, v1 = v1, verbose = FALSE)

# Output
#    Species Petal.Length  Petal.Width 
# 0.03228640   0.04725654   0.06109352 
```

The only overhead is that the univariate partial dependence function of v1 is calculated for each v2, which should typically be acceptable.

**Comment by lang-benjamin** [comment]
Thanks very much! For some reason I thought that `v` still needs to include all variables. Your alternate solution looks good.
