### ISSUE TITLE
parallelization / explicit use of # of CPUs

### ISSUE THREAD

**Issue by KarlKoe** [mayer79/hstats#124]
First of all thanks so much for this great package, it's really super useful and performant! What I wanted to ask is whether there is any way to explicitly choose the number of cores the functions like `hstats()` should use at max. It seems per default all available cores are used - for heavy lifting tasks (like a survival RF object with thousands of samples) I tend to set it to max-1 as otherwise the compute instance may crash or show otherwise funny behavior. Any hints here would be much appreciated, thank you.

**Comment by mayer79** [comment]
Great to hear! The functions in the package are not parallelized so far. It *could* be added to `hstats()` though. Currently, parallel calculations happen only in the predict() calls of the model. If there is a `nthread` parameter in `predict()`, you can pass the corresponding argument via `...`.

**Comment by KarlKoe** [comment]
Thanks, that helps! I just saw CPUs going all on 100% for a long time, so good to know this happens when `predict()` is called.
