### ISSUE TITLE
ICE/PDP computation and plotting for survival - restricting time point range

### ISSUE THREAD

**Issue by KarlKoe** [mayer79/hstats#126]
Dear @mayer79 , I was wondering if there is any easy (maybe obvious?) way to restrict ICE / PDP computation and plotting to a selected number of time points in a ranger survival RF setting. In the real life setting, one has dozens of time points for which ICE / PDP can be computed and plotted which requires lengthy computation times and produces too many, not really informative plots. Like, usually I would choose maybe around 4 time points only to see what's going on. Thanks for any feedback on this.

**Comment by mayer79** [comment]
You can do it via `ranger(, time.interest = ...)`

```
library(hstats)
library(ranger)
library(survival)

fit <- ranger(Surv(time, status) ~ ., data = veteran, time.interest = c(50, 100, 150, 200))
pd <- partial_dep(fit, v = "age", X = veteran)
plot(pd)
```

**Comment by KarlKoe** [comment]
Thanks, for the quick reply. However, this would change the model itself. I'm rather talking about flexible, post-hoc selection of time points of interest based on a final model including all time points.

**Comment by mayer79** [comment]
It is the only way to do it fast. Otherwise, ranger will predict all time points. It would be nice to be able to pass the info to the predict function of ranger, but I don't see this option.

### Slow

```r
library(hstats)
library(ranger)
library(survival)

fit <- ranger(Surv(time, status) ~ ., data = veteran)
pf <- function(m, x) {
  pred <- predict(m, x)
  out <- pred$surv
  colnames(out) <- pred$unique.death.times
  out[, c("49", "100", "151")]
}
pd <- partial_dep(fit, v = "age", X = veteran, pred_fun = pf)
plot(pd)
```

**Comment by KarlKoe** [comment]
Ok thanks a lot, got it!
