### ISSUE TITLE
Interaction effect for multiple features across MultiClass 

### ISSUE THREAD

**Issue by araimacarol** [mayer79/hstats#58]
I have 5 network class categories and some number of features. The classification model was trained using boost trees (xgboost engine) in Tidymodels. I am using the Shapviz package for XGBOOST for the model interpretation (global, local, and interaction effects of features for each network class).  I would like to quantify how much interaction effect (two-way, three-way,  etc.) is accounted for by the features in each of the network class using  the 'hstats' package. Thanks

**Comment by mayer79** [comment]
Three comments

1. {hstats} is not about SHAP interactions, but about H statistics.
2. It does not calculate H stats of degree > 3.
3. It provides statistics *per class and feature*. There is no statistic that would say "that much effect variability comes from all pairwise interactions of all features". 

If all these points are not a problem for you, feel free to add a simple, working code that generates your model.

**Comment by araimacarol** [comment]
Thanks. 
1. I want the calculate the H statistics. I should have been clear with that. The SHAP interpretation was just explaining what I was doing.
2. And yes I only want 2-3-way interaction
3.  And yes, I would like to calculate the statistics  per class and feature

```r
df=
      num_of_nodes  edges mean_eccentr mean_path_length graph_energy
789693          750 235939     1.944000         1.159986    3182.4374
427904          350    700    10.811429         6.725714     589.9658
856958          200   4217     4.105164         2.381886     610.7255
243627          250   1000    12.604000         7.190490     502.2878
362113         1000 399825     2.000000         1.199550   11525.8113
203697           50    322     2.660000         1.786939     134.5122
        modularity diameter   betw_centr transitivity spectral_radius
789693 0.048724706        2 0.0002128436    0.8834596      641.145734
427904 0.783947959       13 0.0630543032    0.3345571        4.169035
856958 0.482916796        5 0.0274158137    0.6451798       47.945511
243627 0.789382500       16 0.1556597731    0.6201141        8.033292
362113 0.001814923        2 0.0000199444    0.8004671      799.853414
203697 0.139659928        3 0.0456408627    0.3729246       15.614312
       eigen_centr   deg_centr mean_degree   min_cut fiedler_value
789693  0.14419020 0.159985759    629.1707 381.00000  375.54658689
427904  0.57714896 0.005730659      4.0000   1.00000    0.09664804
856958  0.51775594 0.108286353     42.1700  10.37519    4.32095726
243627  0.57815063 0.004016064      8.0000   7.00000    0.05426011
362113  0.04704278 0.039389389    799.6500 761.00000  756.18230366
203697  0.54931571 0.288163265     12.8800   7.00000    5.07201355
       normalized_fiedler_value closeness_centr deg_assort_coef graph_name
789693               0.76488717    0.0011629581    -0.078719168    Spatial
427904               0.02414075    0.0004287733    -0.040795465         SW
856958               0.11592051    0.0021529602     0.409295134    Spatial
243627               0.00677294    0.0005688388    -0.001251564         SW
362113               0.96926854    0.0008345756    -0.003158102         ER
203697               0.56261422    0.0115222549    -0.022250656         SF
```

I have a data frame called df with the above columns, where the last column 'graph_name' is the column containing the classes and the rest of the column are the features used to train the classifier.

```r
%%%%%CODE%%%%%%%%%%%
df1=df%>%
select(-graph_name)

x=colnames(df1)
X_train=data.matrix(df1)
model=extract_workflow(final.fitted.model)    
fit=model$fit$fit$fit
set.seed(782)
system.time(
  s <- hstats(fit, v = x, X = X_train,type = "response",
              n_max = 30L,
              pred_fun = stats::predict,
              w = NULL,
              verbose = FALSE)
)
```

#Note: The class of the fitted model and fit object are as follows
- class(final.fitted.model)="last_fit" "resample_results" "tune_results" "tbl_df"   "tbl"  "data.frame" 
- class(model) = "workflow"
- class(fit)= "xgb.Booster"

when I run the above code, I get this error

```r
Error in wrowmean(pred, ngroups = NROW(grid), w = w) : 
  w must be of length NROW(x) / ngroups.
Timing stopped at: 0 0 0.08
```

Please let me know what I am doing wrong

**Comment by mayer79** [comment]
The error message is a bit strange. What is definitively false is to pass `type = "response"` to the predict function.

What do you get with:

```r
x = setdiff(colnames(df), "graph_name")
model = extract_workflow(final.fitted.model)    
s = hstats(model, v = x, X = df, type = "prob")
```

**Comment by mayer79** [comment]
This works with the new CRAN version of {hstats}:

```r
library(tidymodels)

set.seed(123)
split <- initial_split(iris, prop = 0.7)
iris_train <- training(split)
iris_test <- testing(split)

iris_recipe <- recipe(
  formula = Species ~ .,
  data = iris_train
)

xgb_spec <- boost_tree(
  trees = 100,
  tree_depth = 3,
  learn_rate = 0.1
) %>%
  set_engine("xgboost") %>%
  set_mode("classification")

iris_workflow <- workflow() %>%
  add_recipe(iris_recipe) %>%
  add_model(xgb_spec)

# Train the model
iris_fit <- fit(iris_workflow, data = iris_train)

library(hstats)

H <- hstats(iris_fit, X = iris[-5], type = "prob")
H
# Proportion of prediction variability unexplained by main effects of v:
#    .pred_setosa .pred_versicolor  .pred_virginica 
#     0.003429375      0.101947824      0.077373059 
plot(H, which = 1:3, normalize = FALSE)
```

<img width="676" alt="image" src="https://github.com/mayer79/hstats/assets/16206095/5e1b2b8d-8006-49df-a547-86fede66f067">

**Comment by araimacarol** [comment]
Thanks, it's now working with the solution you provided below. The results are what I expected. 
x = setdiff(colnames(df), "graph_name")
model = extract_workflow(final.fitted.model)    
s = hstats(model, v = x, X = df, type = "prob")

**Comment by mayer79** [comment]
Sweet! Use `summary()` or `h2_overall()` etc. to extract the numbers.

**Comment by araimacarol** [comment]
Thanks. Trying to make sense of the plots and interaction effects etc. Will contact you if I have any other issues

**Comment by mayer79** [comment]
The main question is usually: should the pairwise/three-way statistics be normalized or not.
