### ISSUE TITLE
partial_dep() with BY argument: error for tibble X argument

### ISSUE THREAD

**Issue by RoelVerbelen** [mayer79/hstats#92]
``` r
library(hstats)
library(tibble)

## Dobson (1990) Page 93: Randomized Controlled Trial :
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
df <- data.frame(treatment, outcome, counts) # showing data
glm.D93 <- glm(counts ~ outcome + treatment, family = poisson())

# PD with categorical BY

# Works
partial_dep(glm.D93, v = "outcome", X = df, BY = "treatment")
#> Partial dependence object (9 rows). Extract via $data. Top rows:
#> 
#>   treatment outcome        y
#> 1         1       1 3.044522
#> 2         1       2 2.590267
#> 3         1       3 2.751535

# Does not work
partial_dep(glm.D93, v = "outcome", X = tibble(df), BY = "treatment")
#> Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 3, 0
```
<sup>Created on 2023-10-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Root cause seems to be the different behaviour when subsetting tibbles compared to data frames, see [here](https://tibble.tidyverse.org/reference/subsetting.html).

That gets done [here](https://github.com/mayer79/hstats/blob/0767d3553019a7b0d9bf8cd77edef8a4b7b60d95/R/utils_input.R#L15) in the code for `prepare_by()`.

**Comment by mayer79** [comment]
Tibbles...

Will try:

```r
if (is.data.frame(X)) {
  BY <- X[[by_name]]
} else {
  BY <- X[, by_name]
}
```

This problem might occur at other places as well. I will try to fix it.

**Comment by RoelVerbelen** [comment]
Double brackets should work for both cases, so you should be able to avoid if statements:

```
iris
var = names(iris)[1]
iris[[var]]
tibble(iris)[[var]]
```

**Comment by mayer79** [comment]
That covers the matrix case (tibble is also a data.frame). The same error happens actually also with case weights w.

**Comment by mayer79** [comment]
Very good catch, thanks again!
